//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/FileSystemUtils.java
//

#ifndef _EngineFileSystemUtils_H_
#define _EngineFileSystemUtils_H_

@class JavaIoFile;
@protocol JavaUtilList;

#include "J2ObjC_header.h"

@interface EngineFileSystemUtils : NSObject {
}

- (instancetype)init;

- (jboolean)findFilesInFolderWithJavaIoFile:(JavaIoFile *)folder
                           withJavaUtilList:(id<JavaUtilList>)list;

@end

FOUNDATION_EXPORT BOOL EngineFileSystemUtils_initialized;
J2OBJC_STATIC_INIT(EngineFileSystemUtils)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *EngineFileSystemUtils_LOG_TAG_;
J2OBJC_STATIC_FIELD_GETTER(EngineFileSystemUtils, LOG_TAG_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(EngineFileSystemUtils, LOG_TAG_, NSString *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineFileSystemUtils)

#endif // _EngineFileSystemUtils_H_
