//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/FileFilter.java
//

#ifndef _EngineFileFilter_H_
#define _EngineFileFilter_H_

@class IOSObjectArray;
@class JavaIoFile;

#include "J2ObjC_header.h"

@interface EngineFileFilter : NSObject {
}

+ (jboolean)isImageWithJavaIoFile:(JavaIoFile *)file;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL EngineFileFilter_initialized;
J2OBJC_STATIC_INIT(EngineFileFilter)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT jboolean EngineFileFilter_isImageWithJavaIoFile_(JavaIoFile *file);

FOUNDATION_EXPORT IOSObjectArray *EngineFileFilter_imageFileExtensions_;
J2OBJC_STATIC_FIELD_GETTER(EngineFileFilter, imageFileExtensions_, IOSObjectArray *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineFileFilter)

#endif // _EngineFileFilter_H_
