//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/FileSystem.java
//

#ifndef _EngineFileSystem_H_
#define _EngineFileSystem_H_

@class EngineFileSystem_PredefinedFoldersEnum;
@class EngineLocalFolder;

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

@protocol EngineFileSystem < NSObject, JavaObject >

- (EngineLocalFolder *)getFolderWithEngineFileSystem_PredefinedFoldersEnum:(EngineFileSystem_PredefinedFoldersEnum *)folderIndex;

@end

J2OBJC_EMPTY_STATIC_INIT(EngineFileSystem)

J2OBJC_TYPE_LITERAL_HEADER(EngineFileSystem)

typedef NS_ENUM(NSUInteger, EngineFileSystem_PredefinedFolders) {
  EngineFileSystem_PredefinedFolders_ROOT = 0,
  EngineFileSystem_PredefinedFolders_STORAGE = 1,
  EngineFileSystem_PredefinedFolders_DCIM = 2,
  EngineFileSystem_PredefinedFolders_DOWNLOADS = 3,
  EngineFileSystem_PredefinedFolders_MUSIC = 4,
  EngineFileSystem_PredefinedFolders_PICTURES = 5,
  EngineFileSystem_PredefinedFolders_DOCUMENTS = 6,
  EngineFileSystem_PredefinedFolders_MOVIES = 7,
};

@interface EngineFileSystem_PredefinedFoldersEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *EngineFileSystem_PredefinedFoldersEnum_values();

+ (EngineFileSystem_PredefinedFoldersEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT EngineFileSystem_PredefinedFoldersEnum *EngineFileSystem_PredefinedFoldersEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL EngineFileSystem_PredefinedFoldersEnum_initialized;
J2OBJC_STATIC_INIT(EngineFileSystem_PredefinedFoldersEnum)

FOUNDATION_EXPORT EngineFileSystem_PredefinedFoldersEnum *EngineFileSystem_PredefinedFoldersEnum_values_[];

#define EngineFileSystem_PredefinedFoldersEnum_ROOT EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_ROOT]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, ROOT)

#define EngineFileSystem_PredefinedFoldersEnum_STORAGE EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_STORAGE]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, STORAGE)

#define EngineFileSystem_PredefinedFoldersEnum_DCIM EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_DCIM]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, DCIM)

#define EngineFileSystem_PredefinedFoldersEnum_DOWNLOADS EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_DOWNLOADS]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, DOWNLOADS)

#define EngineFileSystem_PredefinedFoldersEnum_MUSIC EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_MUSIC]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, MUSIC)

#define EngineFileSystem_PredefinedFoldersEnum_PICTURES EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_PICTURES]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, PICTURES)

#define EngineFileSystem_PredefinedFoldersEnum_DOCUMENTS EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_DOCUMENTS]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, DOCUMENTS)

#define EngineFileSystem_PredefinedFoldersEnum_MOVIES EngineFileSystem_PredefinedFoldersEnum_values_[EngineFileSystem_PredefinedFolders_MOVIES]
J2OBJC_ENUM_CONSTANT_GETTER(EngineFileSystem_PredefinedFoldersEnum, MOVIES)

J2OBJC_TYPE_LITERAL_HEADER(EngineFileSystem_PredefinedFoldersEnum)

#endif // _EngineFileSystem_H_
