//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/FileLoaderCallbacks.java
//

#ifndef _EngineFileLoaderCallbacks_H_
#define _EngineFileLoaderCallbacks_H_

@class EngineFileSystem_PredefinedFoldersEnum;
@class EngineLocalFolder;

#include "J2ObjC_header.h"

@protocol EngineFileLoaderCallbacks < NSObject, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(EngineFileLoaderCallbacks)

J2OBJC_TYPE_LITERAL_HEADER(EngineFileLoaderCallbacks)

@protocol EngineFileLoaderCallbacks_FragmentLoaderCallbacks < NSObject, JavaObject >

- (void)showFileListFragmentWithEngineFileSystem_PredefinedFoldersEnum:(EngineFileSystem_PredefinedFoldersEnum *)folderIndex;

- (void)showFileListFragmentWithEngineLocalFolder:(EngineLocalFolder *)folder
                                      withBoolean:(jboolean)clearBackStack
                                      withBoolean:(jboolean)addToBackStack;

@end

J2OBJC_EMPTY_STATIC_INIT(EngineFileLoaderCallbacks_FragmentLoaderCallbacks)

J2OBJC_TYPE_LITERAL_HEADER(EngineFileLoaderCallbacks_FragmentLoaderCallbacks)

#endif // _EngineFileLoaderCallbacks_H_
