//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/FileSystem.java
//

#include "FileSystem.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LocalFolder.h"
#include "java/lang/IllegalArgumentException.h"

@interface EngineFileSystem : NSObject
@end

@implementation EngineFileSystem

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getFolderWithEngineFileSystem_PredefinedFoldersEnum:", "getFolder", "Lengine.LocalFolder;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _EngineFileSystem = { 1, "FileSystem", "engine", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_EngineFileSystem;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EngineFileSystem)

BOOL EngineFileSystem_PredefinedFoldersEnum_initialized = NO;

EngineFileSystem_PredefinedFoldersEnum *EngineFileSystem_PredefinedFoldersEnum_values_[8];

@implementation EngineFileSystem_PredefinedFoldersEnum

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

IOSObjectArray *EngineFileSystem_PredefinedFoldersEnum_values() {
  EngineFileSystem_PredefinedFoldersEnum_init();
  return [IOSObjectArray arrayWithObjects:EngineFileSystem_PredefinedFoldersEnum_values_ count:8 type:EngineFileSystem_PredefinedFoldersEnum_class_()];
}
+ (IOSObjectArray *)values {
  return EngineFileSystem_PredefinedFoldersEnum_values();
}

+ (EngineFileSystem_PredefinedFoldersEnum *)valueOfWithNSString:(NSString *)name {
  return EngineFileSystem_PredefinedFoldersEnum_valueOfWithNSString_(name);
}

EngineFileSystem_PredefinedFoldersEnum *EngineFileSystem_PredefinedFoldersEnum_valueOfWithNSString_(NSString *name) {
  EngineFileSystem_PredefinedFoldersEnum_init();
  for (int i = 0; i < 8; i++) {
    EngineFileSystem_PredefinedFoldersEnum *e = EngineFileSystem_PredefinedFoldersEnum_values_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[[JavaLangIllegalArgumentException alloc] initWithNSString:name] autorelease];
  return nil;
}

- (id)copyWithZone:(NSZone *)zone {
  return [self retain];
}

+ (void)initialize {
  if (self == [EngineFileSystem_PredefinedFoldersEnum class]) {
    EngineFileSystem_PredefinedFoldersEnum_ROOT = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"ROOT" withInt:0];
    EngineFileSystem_PredefinedFoldersEnum_STORAGE = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"STORAGE" withInt:1];
    EngineFileSystem_PredefinedFoldersEnum_DCIM = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"DCIM" withInt:2];
    EngineFileSystem_PredefinedFoldersEnum_DOWNLOADS = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"DOWNLOADS" withInt:3];
    EngineFileSystem_PredefinedFoldersEnum_MUSIC = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"MUSIC" withInt:4];
    EngineFileSystem_PredefinedFoldersEnum_PICTURES = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"PICTURES" withInt:5];
    EngineFileSystem_PredefinedFoldersEnum_DOCUMENTS = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"DOCUMENTS" withInt:6];
    EngineFileSystem_PredefinedFoldersEnum_MOVIES = [[EngineFileSystem_PredefinedFoldersEnum alloc] initWithNSString:@"MOVIES" withInt:7];
    J2OBJC_SET_INITIALIZED(EngineFileSystem_PredefinedFoldersEnum)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithNSString:withInt:", "init", NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "ROOT", "ROOT", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_ROOT,  },
    { "STORAGE", "STORAGE", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_STORAGE,  },
    { "DCIM", "DCIM", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_DCIM,  },
    { "DOWNLOADS", "DOWNLOADS", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_DOWNLOADS,  },
    { "MUSIC", "MUSIC", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_MUSIC,  },
    { "PICTURES", "PICTURES", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_PICTURES,  },
    { "DOCUMENTS", "DOCUMENTS", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_DOCUMENTS,  },
    { "MOVIES", "MOVIES", 0x4019, "Lengine.FileSystem$PredefinedFolders;", &EngineFileSystem_PredefinedFoldersEnum_MOVIES,  },
  };
  static const char *superclass_type_args[] = {"Lengine.FileSystem$PredefinedFolders;"};
  static const J2ObjcClassInfo _EngineFileSystem_PredefinedFoldersEnum = { 1, "PredefinedFolders", "engine", "FileSystem", 0x4019, 1, methods, 8, fields, 1, superclass_type_args};
  return &_EngineFileSystem_PredefinedFoldersEnum;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EngineFileSystem_PredefinedFoldersEnum)
