//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/FileSystemUtils.java
//

#include "FileSystemUtils.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "java/io/File.h"
#include "java/util/List.h"

BOOL EngineFileSystemUtils_initialized = NO;

@implementation EngineFileSystemUtils

NSString * EngineFileSystemUtils_LOG_TAG_;

- (instancetype)init {
  return [super init];
}

- (jboolean)findFilesInFolderWithJavaIoFile:(JavaIoFile *)folder
                           withJavaUtilList:(id<JavaUtilList>)list {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

+ (void)initialize {
  if (self == [EngineFileSystemUtils class]) {
    JreStrongAssign(&EngineFileSystemUtils_LOG_TAG_, nil, [EngineFileSystemUtils_class_() getSimpleName]);
    J2OBJC_SET_INITIALIZED(EngineFileSystemUtils)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "init", "FileSystemUtils", NULL, 0x1, NULL },
    { "findFilesInFolderWithJavaIoFile:withJavaUtilList:", "findFilesInFolder", "Z", 0x401, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "LOG_TAG_", NULL, 0x9, "Ljava.lang.String;", &EngineFileSystemUtils_LOG_TAG_,  },
  };
  static const J2ObjcClassInfo _EngineFileSystemUtils = { 1, "FileSystemUtils", "engine", NULL, 0x401, 2, methods, 1, fields, 0, NULL};
  return &_EngineFileSystemUtils;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EngineFileSystemUtils)
