//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Running/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/Java2ObjcExampleClass.java
//

#ifndef _EngineJava2ObjcExampleClass_H_
#define _EngineJava2ObjcExampleClass_H_

#include "J2ObjC_header.h"

@interface EngineJava2ObjcExampleClass : NSObject {
}

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(EngineJava2ObjcExampleClass)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineJava2ObjcExampleClass)

#endif // _EngineJava2ObjcExampleClass_H_
