//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFile.java
//

#include "J2ObjC_source.h"
#include "LocalFile.h"
#include "java/io/File.h"

@interface EngineLocalFile : NSObject
@end

@implementation EngineLocalFile

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getDisplayName", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "getDisplayThumbnail", NULL, "I", 0x401, NULL },
    { "getPath", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "getFile", NULL, "Ljava.io.File;", 0x401, NULL },
    { "getUriAsString", NULL, "Ljava.lang.String;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _EngineLocalFile = { 1, "LocalFile", "engine", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_EngineLocalFile;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(EngineLocalFile)
