//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFolder.java
//

#include "FileSystemUtils.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LocalFolder.h"
#include "Thumbnail.h"
#include "java/io/File.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface EngineLocalFolder () {
 @public
  JavaIoFile *mFile_;
  id<JavaUtilList> mChildFiles_;
}
@end

J2OBJC_FIELD_SETTER(EngineLocalFolder, mFile_, JavaIoFile *)
J2OBJC_FIELD_SETTER(EngineLocalFolder, mChildFiles_, id<JavaUtilList>)

BOOL EngineLocalFolder_initialized = NO;

@implementation EngineLocalFolder

NSString * EngineLocalFolder_LOG_TAG_;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file {
  if (self = [super init]) {
    EngineLocalFolder_set_mFile_(self, file);
  }
  return self;
}

- (id<JavaUtilList>)getChildFilesWithEngineFileSystemUtils:(EngineFileSystemUtils *)fileSystem {
  if (mChildFiles_ == nil) {
    EngineLocalFolder_setAndConsume_mChildFiles_(self, [[JavaUtilArrayList alloc] init]);
    if ([((EngineFileSystemUtils *) nil_chk(fileSystem)) findFilesInFolderWithJavaIoFile:mFile_ withJavaUtilList:mChildFiles_]) {
      return mChildFiles_;
    }
    else {
      return mChildFiles_;
    }
  }
  else {
    return mChildFiles_;
  }
}

- (NSString *)getDisplayName {
  if (mFile_ != nil) {
    return [mFile_ getName];
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("$$", EngineLocalFolder_LOG_TAG_, @": Cannot return correct folder name. Got null pointer.")];
    return @"";
  }
}

- (jint)getDisplayThumbnail {
  return [((EngineThumbnail *) nil_chk(mThumbnail_)) getResourceId];
}

- (NSString *)getPath {
  if (mFile_ != nil) {
    return [mFile_ getPath];
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("$$", EngineLocalFolder_LOG_TAG_, @": Cannot return correct path. Got null pointer.")];
    return @"";
  }
}

- (void)setPredefinedThumbnailWithInt:(jint)resourceId {
  [((EngineThumbnail *) nil_chk(mThumbnail_)) setResourceIdWithInt:resourceId];
}

- (JavaIoFile *)getFile {
  if (mFile_ != nil) {
    return mFile_;
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("$$", EngineLocalFolder_LOG_TAG_, @": Cannot return file. Got null pointer.")];
    return nil;
  }
}

- (NSString *)getUriAsString {
  return nil;
}

- (void)dealloc {
  RELEASE_(mFile_);
  RELEASE_(mChildFiles_);
  RELEASE_(mThumbnail_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(EngineLocalFolder *)other {
  [super copyAllFieldsTo:other];
  EngineLocalFolder_set_mFile_(other, mFile_);
  EngineLocalFolder_set_mChildFiles_(other, mChildFiles_);
  EngineLocalFolder_set_mThumbnail_(other, mThumbnail_);
}

+ (void)initialize {
  if (self == [EngineLocalFolder class]) {
    JreStrongAssign(&EngineLocalFolder_LOG_TAG_, nil, [EngineLocalFolder_class_() getSimpleName]);
    J2OBJC_SET_INITIALIZED(EngineLocalFolder)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoFile:", "LocalFolder", NULL, 0x1, NULL },
    { "getChildFilesWithEngineFileSystemUtils:", "getChildFiles", "Ljava.util.List;", 0x1, NULL },
    { "getDisplayName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getDisplayThumbnail", NULL, "I", 0x1, NULL },
    { "getPath", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "setPredefinedThumbnailWithInt:", "setPredefinedThumbnail", "V", 0x1, NULL },
    { "getFile", NULL, "Ljava.io.File;", 0x1, NULL },
    { "getUriAsString", NULL, "Ljava.lang.String;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "LOG_TAG_", NULL, 0xa, "Ljava.lang.String;", &EngineLocalFolder_LOG_TAG_,  },
    { "mFile_", NULL, 0x2, "Ljava.io.File;", NULL,  },
    { "mChildFiles_", NULL, 0x2, "Ljava.util.List;", NULL,  },
    { "mThumbnail_", NULL, 0x4, "Lengine.Thumbnail;", NULL,  },
  };
  static const J2ObjcClassInfo _EngineLocalFolder = { 1, "LocalFolder", "engine", NULL, 0x401, 8, methods, 4, fields, 0, NULL};
  return &_EngineLocalFolder;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EngineLocalFolder)
