//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFolder.java
//

#ifndef _EngineLocalFolder_H_
#define _EngineLocalFolder_H_

@class EngineFileSystemUtils;
@class EngineThumbnail;
@class JavaIoFile;
@protocol JavaUtilList;

#include "J2ObjC_header.h"
#include "LocalFile.h"
#include "java/io/Serializable.h"

@interface EngineLocalFolder : NSObject < EngineLocalFile, JavaIoSerializable > {
 @public
  EngineThumbnail *mThumbnail_;
}

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file;

- (id<JavaUtilList>)getChildFilesWithEngineFileSystemUtils:(EngineFileSystemUtils *)fileSystem;

- (NSString *)getDisplayName;

- (jint)getDisplayThumbnail;

- (NSString *)getPath;

- (void)setPredefinedThumbnailWithInt:(jint)resourceId;

- (JavaIoFile *)getFile;

- (NSString *)getUriAsString;

@end

FOUNDATION_EXPORT BOOL EngineLocalFolder_initialized;
J2OBJC_STATIC_INIT(EngineLocalFolder)

J2OBJC_FIELD_SETTER(EngineLocalFolder, mThumbnail_, EngineThumbnail *)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *EngineLocalFolder_LOG_TAG_;
J2OBJC_STATIC_FIELD_GETTER(EngineLocalFolder, LOG_TAG_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(EngineLocalFolder, LOG_TAG_, NSString *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineLocalFolder)

#endif // _EngineLocalFolder_H_
