//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFile.java
//

#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LocalFile.h"
#include "Thumbnail.h"
#include "java/io/File.h"
#include "java/io/PrintStream.h"
#include "java/lang/System.h"

@interface EngineLocalFile () {
}
@end

BOOL EngineLocalFile_initialized = NO;

@implementation EngineLocalFile

NSString * EngineLocalFile_LOG_TAG_;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file {
  if (self = [super init]) {
    EngineLocalFile_set_mFile_(self, file);
  }
  return self;
}

- (NSString *)getDisplayName {
  if (mFile_ != nil) {
    return [mFile_ getName];
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("$$", EngineLocalFile_LOG_TAG_, @" Cannot return correct path. Got null pointer.")];
    return @"";
  }
}

- (jint)getDisplayThumbnail {
  return [((EngineThumbnail *) nil_chk(mThumbnail_)) getResourceId];
}

- (NSString *)getPath {
  if (mFile_ != nil) {
    return [mFile_ getParent];
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("$$", EngineLocalFile_LOG_TAG_, @" Cannot return correct file path. Got null pointer.")];
    return @"";
  }
}

- (JavaIoFile *)getFile {
  if (mFile_ != nil) {
    return mFile_;
  }
  else {
    [((JavaIoPrintStream *) nil_chk(JavaLangSystem_get_out_())) printlnWithNSString:JreStrcat("$$", EngineLocalFile_LOG_TAG_, @" Cannot return file. Got null pointer.")];
    return nil;
  }
}

- (NSString *)getUriAsString {
  return nil;
}

- (void)dealloc {
  RELEASE_(mFile_);
  RELEASE_(mThumbnail_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(EngineLocalFile *)other {
  [super copyAllFieldsTo:other];
  EngineLocalFile_set_mFile_(other, mFile_);
  EngineLocalFile_set_mThumbnail_(other, mThumbnail_);
}

+ (void)initialize {
  if (self == [EngineLocalFile class]) {
    JreStrongAssign(&EngineLocalFile_LOG_TAG_, nil, [EngineLocalFile_class_() getSimpleName]);
    J2OBJC_SET_INITIALIZED(EngineLocalFile)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoFile:", "LocalFile", NULL, 0x1, NULL },
    { "getDisplayName", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getDisplayThumbnail", NULL, "I", 0x1, NULL },
    { "getPath", NULL, "Ljava.lang.String;", 0x1, NULL },
    { "getFile", NULL, "Ljava.io.File;", 0x1, NULL },
    { "getUriAsString", NULL, "Ljava.lang.String;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "LOG_TAG_", NULL, 0xa, "Ljava.lang.String;", &EngineLocalFile_LOG_TAG_,  },
    { "mFile_", NULL, 0x4, "Ljava.io.File;", NULL,  },
    { "mThumbnail_", NULL, 0x4, "Lengine.Thumbnail;", NULL,  },
  };
  static const J2ObjcClassInfo _EngineLocalFile = { 1, "LocalFile", "engine", NULL, 0x401, 6, methods, 3, fields, 0, NULL};
  return &_EngineLocalFile;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EngineLocalFile)
