//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFile.java
//

#ifndef _EngineLocalFile_H_
#define _EngineLocalFile_H_

@class EngineThumbnail;
@class JavaIoFile;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface EngineLocalFile : NSObject < JavaIoSerializable > {
 @public
  JavaIoFile *mFile_;
  EngineThumbnail *mThumbnail_;
}

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file;

- (NSString *)getDisplayName;

- (jint)getDisplayThumbnail;

- (NSString *)getPath;

- (JavaIoFile *)getFile;

- (NSString *)getUriAsString;

@end

FOUNDATION_EXPORT BOOL EngineLocalFile_initialized;
J2OBJC_STATIC_INIT(EngineLocalFile)

J2OBJC_FIELD_SETTER(EngineLocalFile, mFile_, JavaIoFile *)
J2OBJC_FIELD_SETTER(EngineLocalFile, mThumbnail_, EngineThumbnail *)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *EngineLocalFile_LOG_TAG_;
J2OBJC_STATIC_FIELD_GETTER(EngineLocalFile, LOG_TAG_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(EngineLocalFile, LOG_TAG_, NSString *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineLocalFile)

#endif // _EngineLocalFile_H_
