//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFolder.java
//

#include "FileSystemUtils.h"
#include "IOSClass.h"
#include "J2ObjC_source.h"
#include "LocalFolder.h"
#include "java/io/File.h"
#include "java/util/ArrayList.h"
#include "java/util/List.h"

@interface EngineLocalFolder () {
 @public
  id<JavaUtilList> mChildFiles_;
}
@end

J2OBJC_FIELD_SETTER(EngineLocalFolder, mChildFiles_, id<JavaUtilList>)

BOOL EngineLocalFolder_initialized = NO;

@implementation EngineLocalFolder

NSString * EngineLocalFolder_LOG_TAG_;

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file {
  return [super initWithJavaIoFile:file];
}

- (id<JavaUtilList>)getChildFilesWithEngineFileSystemUtils:(EngineFileSystemUtils *)fileSystem {
  if (mChildFiles_ == nil) {
    EngineLocalFolder_setAndConsume_mChildFiles_(self, [[JavaUtilArrayList alloc] init]);
    if ([((EngineFileSystemUtils *) nil_chk(fileSystem)) findFilesInFolderWithJavaIoFile:mFile_ withJavaUtilList:mChildFiles_]) {
      return mChildFiles_;
    }
    else {
      return mChildFiles_;
    }
  }
  else {
    return mChildFiles_;
  }
}

- (void)dealloc {
  RELEASE_(mChildFiles_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(EngineLocalFolder *)other {
  [super copyAllFieldsTo:other];
  EngineLocalFolder_set_mChildFiles_(other, mChildFiles_);
}

+ (void)initialize {
  if (self == [EngineLocalFolder class]) {
    JreStrongAssign(&EngineLocalFolder_LOG_TAG_, nil, [EngineLocalFolder_class_() getSimpleName]);
    J2OBJC_SET_INITIALIZED(EngineLocalFolder)
  }
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithJavaIoFile:", "LocalFolder", NULL, 0x1, NULL },
    { "getChildFilesWithEngineFileSystemUtils:", "getChildFiles", "Ljava.util.List;", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "LOG_TAG_", NULL, 0xa, "Ljava.lang.String;", &EngineLocalFolder_LOG_TAG_,  },
    { "mChildFiles_", NULL, 0x2, "Ljava.util.List;", NULL,  },
  };
  static const J2ObjcClassInfo _EngineLocalFolder = { 1, "LocalFolder", "engine", NULL, 0x401, 2, methods, 2, fields, 0, NULL};
  return &_EngineLocalFolder;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EngineLocalFolder)
