//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFolder.java
//

#ifndef _EngineLocalFolder_H_
#define _EngineLocalFolder_H_

@class EngineFileSystemUtils;
@class JavaIoFile;
@protocol JavaUtilList;

#include "J2ObjC_header.h"
#include "LocalFile.h"
#include "java/io/Serializable.h"

@interface EngineLocalFolder : EngineLocalFile < JavaIoSerializable > {
}

- (instancetype)initWithJavaIoFile:(JavaIoFile *)file;

- (id<JavaUtilList>)getChildFilesWithEngineFileSystemUtils:(EngineFileSystemUtils *)fileSystem;

@end

FOUNDATION_EXPORT BOOL EngineLocalFolder_initialized;
J2OBJC_STATIC_INIT(EngineLocalFolder)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT NSString *EngineLocalFolder_LOG_TAG_;
J2OBJC_STATIC_FIELD_GETTER(EngineLocalFolder, LOG_TAG_, NSString *)
J2OBJC_STATIC_FIELD_SETTER(EngineLocalFolder, LOG_TAG_, NSString *)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineLocalFolder)

#endif // _EngineLocalFolder_H_
