//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/LocalFile.java
//

#ifndef _EngineLocalFile_H_
#define _EngineLocalFile_H_

@class JavaIoFile;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@protocol EngineLocalFile < JavaIoSerializable, NSObject, JavaObject >
- (NSString *)getDisplayName;

- (jint)getDisplayThumbnail;

- (NSString *)getPath;

- (JavaIoFile *)getFile;

- (NSString *)getUriAsString;

@end

J2OBJC_EMPTY_STATIC_INIT(EngineLocalFile)

J2OBJC_TYPE_LITERAL_HEADER(EngineLocalFile)

#endif // _EngineLocalFile_H_
