//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Github/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/Thumbnail.java
//

#include "J2ObjC_source.h"
#include "LocalFile.h"
#include "LocalFolder.h"
#include "Thumbnail.h"

@interface EngineThumbnail () {
 @public
  jint mResourceId_;
}
@end

@implementation EngineThumbnail

jint EngineThumbnail_NOT_DEFINED_ = 0;

- (instancetype)initWithEngineLocalFile:(EngineLocalFile *)file {
  if (self = [super init]) {
    mResourceId_ = EngineThumbnail_NOT_DEFINED_;
    if ([file isKindOfClass:[EngineLocalFolder class]]) {
      mResourceId_ = [self getDefaultFolderResourceId];
    }
    else {
      mResourceId_ = [self getDefaultFileResourceId];
    }
  }
  return self;
}

- (jint)getDefaultFileResourceId {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jint)getDefaultFolderResourceId {
  // can't call an abstract method
  [self doesNotRecognizeSelector:_cmd];
  return 0;
}

- (jint)getResourceId {
  return mResourceId_;
}

- (void)setResourceIdWithInt:(jint)mResourceId {
  self->mResourceId_ = mResourceId;
}

- (void)copyAllFieldsTo:(EngineThumbnail *)other {
  [super copyAllFieldsTo:other];
  other->mResourceId_ = mResourceId_;
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithEngineLocalFile:", "Thumbnail", NULL, 0x1, NULL },
    { "getDefaultFileResourceId", NULL, "I", 0x401, NULL },
    { "getDefaultFolderResourceId", NULL, "I", 0x401, NULL },
    { "getResourceId", NULL, "I", 0x1, NULL },
    { "setResourceIdWithInt:", "setResourceId", "V", 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "NOT_DEFINED_", NULL, 0x9, "I", &EngineThumbnail_NOT_DEFINED_,  },
    { "mResourceId_", NULL, 0x2, "I", NULL,  },
  };
  static const J2ObjcClassInfo _EngineThumbnail = { 1, "Thumbnail", "engine", NULL, 0x401, 5, methods, 2, fields, 0, NULL};
  return &_EngineThumbnail;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(EngineThumbnail)
