//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/dmitrymalkovich/Documents/Developer/Active/hybrid-app-sample/file-explorer_android/app/src/main/java/engine/Thumbnail.java
//

#ifndef _EngineThumbnail_H_
#define _EngineThumbnail_H_

@protocol EngineLocalFile;

#include "J2ObjC_header.h"
#include "java/io/Serializable.h"

@interface EngineThumbnail : NSObject < JavaIoSerializable > {
}

- (instancetype)initWithEngineLocalFile:(id<EngineLocalFile>)file;

- (jint)getDefaultFileResourceId;

- (jint)getDefaultFolderResourceId;

- (jint)getResourceId;

- (void)setResourceIdWithInt:(jint)mResourceId;

@end

J2OBJC_EMPTY_STATIC_INIT(EngineThumbnail)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT jint EngineThumbnail_NOT_DEFINED_;
J2OBJC_STATIC_FIELD_GETTER(EngineThumbnail, NOT_DEFINED_, jint)
J2OBJC_STATIC_FIELD_REF_GETTER(EngineThumbnail, NOT_DEFINED_, jint)
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(EngineThumbnail)

#endif // _EngineThumbnail_H_
